// esbuild.mjs — build script for the OpenRouter PDF Translator plugin.
//
// Based on the standard obsidian-sample-plugin configuration, extended with
// the pdfjs-dist community-plugin compliance patch (see pdfjsPatchPlugin
// below) and a post-build self-check that fails the build if the bundle
// regresses (pdfjs not bundled / forbidden patterns re-introduced).
//
// IMPORTANT:
//   - `pdfjs-dist` and `dompurify` must NOT be listed in `external` — they
//     are runtime dependencies bundled INTO main.js (the installed plugin
//     folder has no node_modules).
//   - pdfjs-dist must stay pinned to 3.11.174 (see pdf-text-extractor.ts
//     header comment for the full rationale).
//
// NOTE: this repo uses a FLAT layout — main.ts sits next to main.js, esbuild.mjs
// and package.json in the repository root (no src/ folder).

import * as esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// ─────────────────────────────────────────────────────────────────────────
// pdfjs-dist community-plugin compliance patch.
//
// pdf.js 3.11.174 ships a few code patterns that the Obsidian community-
// plugin validator flags, even though they are unreachable in this plugin's
// configuration (we always pass PDF bytes directly and register the bundled
// worker — pdf.js never performs network loads or script injection at
// runtime). The patch rewrites those exact, unreachable strings at BUILD
// time so they never appear in main.js:
//
//   1. loadScript(): `document.createElement("script")` — dynamic <script>
//      creation (the check that produced
//      "Found 1 dynamic <script> element creation"). Unreachable because
//      pdf-text-extractor.ts registers `globalThis.pdfjsWorker`
//      (pdf.js worker-resolution PATH A), so loadScript (PATH C) is never
//      called. Patched to create an inert element instead.
//
//   2. Fake-worker PATH B: `eval("require")` — eval usage (separate
//      validator check). Node-only branch, never taken in Obsidian
//      (isNodeJS is false in the Electron renderer). Patched to a plain
//      `require` reference.
//
//   3. FeatureTest.isEvalSupported probe: `new Function("")` — patched to
//      throw, making isEvalSupported() deterministically false.
//
//   4. Compiled glyph / PostScript function constructors:
//      `new Function("c", "size", jsBuf.join(""))` and
//      `new Function("src", "srcOffset", "dest", "destOffset", compiled)` —
//      guarded by isEvalSupported (probe above) AND the plugin passes
//      `isEvalSupported: false` to every getDocument call, so the
//      interpreter path is always used. Patched to loud throws so any
//      future regression surfaces immediately.
//
// Every replacement targets an exact, unique string in the pdfjs source;
// if a future pdfjs-dist upgrade changes the formatting, the build FAILS
// with a clear error (see assertions below) instead of silently shipping
// flagged code.
// ─────────────────────────────────────────────────────────────────────────
const PDFJS_PATCHES = [
  {
    file: "pdf.js",
    find: 'const script = document.createElement("script");',
    replace:
      'const script = document.createElement("pdfjs-script-disabled-in-obsidian-build");',
    note: "dynamic <script> creation (validator blocker) — unreachable via PATH A",
  },
  {
    file: "pdf.js",
    find: 'eval("require")(this.workerSrc)',
    replace: 'require(this.workerSrc)',
    note: 'eval("require") in Node-only fake-worker PATH B',
  },
  {
    file: "pdf.js",
    find: 'new Function("");',
    replace: 'throw new Error("eval disabled in Obsidian community build");',
    note: "isEvalSupported feature probe",
  },
  {
    file: "pdf.worker.js",
    find: 'new Function("");',
    replace: 'throw new Error("eval disabled in Obsidian community build");',
    note: "isEvalSupported feature probe (worker copy)",
  },
  {
    file: "pdf.js",
    find: 'return this.compiledGlyphs[character] = new Function("c", "size", jsBuf.join(""));',
    replace: 'throw new Error("eval disabled in Obsidian community build");',
    note: "compiled glyph constructor (isEvalSupported-guarded)",
  },
  {
    file: "pdf.worker.js",
    find: 'return new Function("src", "srcOffset", "dest", "destOffset", compiled);',
    replace: 'throw new Error("eval disabled in Obsidian community build");',
    note: "PostScript function compiler (isEvalSupported-guarded)",
  },
];

const pdfjsPatchPlugin = {
  name: "pdfjs-community-patch",
  setup(build) {
    build.onLoad({ filter: /pdfjs-dist[\\/](legacy[\\/])?build[\\/]pdf(\.worker)?\.js$/ }, async (args) => {
      const fileName = path.basename(args.path);
      let source = fs.readFileSync(args.path, "utf8");
      let touched = false;

      for (const p of PDFJS_PATCHES) {
        if (p.file !== fileName) continue;
        if (!source.includes(p.find)) {
          // Hard fail: the pinned pdfjs-dist copy no longer matches the
          // expected source. Do NOT ship unpatched code silently.
          return {
            errors: [
              {
                text:
                  `pdfjs-community-patch: expected string not found in ${fileName}:\n` +
                  `  ${p.find}\n` +
                  `This build refuses to bundle unpatched pdf.js code (community-plugin ` +
                  `validator compliance). If pdfjs-dist was upgraded, re-audit the new ` +
                  `source and update PDFJS_PATCHES in esbuild.mjs.`,
              },
            ],
          };
        }
        source = source.split(p.find).join(p.replace);
        touched = true;
      }

      if (touched) {
        console.log(`[pdfjs-community-patch] patched ${args.path}`);
        return { contents: source, loader: "js" };
      }
      return null; // untouched file → default loader
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
    // NOTE: intentionally NOT external — must be bundled into main.js:
    //   pdfjs-dist, dompurify
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  // Dev: EXTERNAL sourcemap (main.js.map) — Obsidian loads only main.js, so the
  // dev bundle stays ~4.8 MB instead of ~15 MB with inline maps (faster plugin
  // reloads while developing); DevTools still resolves sources via the emitted
  // `//# sourceMappingURL=main.js.map` comment.
  // Production: no sourcemap — the release artifact must be self-contained.
  sourcemap: prod ? false : true,
  treeShaking: true,
  outfile: "main.js",
  plugins: [pdfjsPatchPlugin],
});

if (prod) {
  await context.rebuild();

  // ── Post-build self-check (community-plugin compliance gate) ──
  const bundle = fs.readFileSync("main.js", "utf8");
  const failures = [];

  const mustContain = [
    ["PDFWorker", "pdfjs-dist library is bundled"],
    ["WorkerMessageHandler", "pdf.js worker is bundled"],
    ["DOMPurify", "dompurify is bundled"],
  ];
  for (const [needle, what] of mustContain) {
    if (!bundle.includes(needle)) failures.push(`FAIL: ${what} (missing "${needle}" in main.js)`);
  }
  if (bundle.length < 1_500_000) {
    failures.push(`FAIL: main.js is only ${(bundle.length / 1024 / 1024).toFixed(2)} MB — pdfjs-dist was NOT bundled (check node_modules / external list)`);
  }

  const mustNotContain = [
    [new RegExp(String.raw`createElement\((["'\`])script`), 'dynamic <script> creation'],
    [new RegExp(String.raw`\beval\s*\(`), "eval() call"],
    [new RegExp(String.raw`new Function`), "new Function constructor"],
    [new RegExp(String.raw`document\.write\s*\(`), "document.write()"],
    [/cdnjs\.cloudflare\.com/, "CDN reference"],
    [/unpkg\.com|jsdelivr\.net|esm\.sh/, "CDN reference"],
  ];
  for (const [re, what] of mustNotContain) {
    if (re.test(bundle)) failures.push(`FAIL: ${what} found in main.js`);
  }

  if (failures.length > 0) {
    console.error("\n┌─ BUILD SELF-CHECK FAILED ─────────────────────────────");
    for (const f of failures) console.error("│ " + f);
    console.error("└─────────────────────────────────────────────────────────\n");
    process.exit(1);
  }

  console.log("\n✓ Build self-check passed: bundle is community-plugin compliant.");
  console.log(`  main.js: ${(bundle.length / 1024 / 1024).toFixed(2)} MB`);
  console.log("  no dynamic <script> creation, no eval, no new Function, no CDN references.\n");
  process.exit(0);
} else {
  console.log("[dev] watch mode: main.js (~4.8 MB) + main.js.map (external sourcemap, debug only)");
  console.log("[dev] main.js.map is NOT loaded by Obsidian — keep it out of releases (.gitignore)");
  console.log("[dev] for the RELEASE build run: npm run build");
  await context.watch();
}
