// esbuild.mjs — the STANDARD Obsidian plugin build, kept as close to
// obsidian-sample-plugin's esbuild.config.mjs as possible (same structure,
// same options, same formatting — diff-friendly against the upstream sample).
//
// Documented deviations from the sample (each marked DEVIATION below):
//   1. entryPoints: ['main.ts'] — this repository is FLAT: main.ts sits in
//      the repo root next to package.json (no src/ folder).
//   2. dev sourcemap is an EXTERNAL .map file (sample uses 'inline'):
//      inline maps made the dev main.js ~15 MB because Obsidian reloads
//      main.js on every plugin reload; the external map keeps dev main.js
//      at ~4.8 MB. Production is identical to the sample: no sourcemap.
//   3. pdfjs-dist and dompurify are NOT in `external` — they are runtime
//      dependencies bundled INTO main.js (the installed plugin has no
//      node_modules). Comment-only deviation; must stay this way.
//
// Build through npm scripts only (`npm run dev` / `npm run build`): they run
// scripts/patch-pdfjs.mjs first, and `npm run build` ends with
// scripts/verify-bundle.mjs. Calling `node esbuild.mjs` directly can bundle
// an UNPATCHED pdfjs-dist (validator rejection) and skips verification.

import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// DEVIATION 1: flat layout — the entry point is in the repo root.
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
		// DEVIATION 3: pdfjs-dist and dompurify are intentionally NOT
		// external — they must be bundled into main.js.
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	// DEVIATION 2: dev = external main.js.map (Obsidian never loads it,
	// DevTools resolves sources through sourceMappingURL); prod = no map.
	sourcemap: prod ? false : true,
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	console.log('[dev] watch: main.js (~4.8 MB, readable) + main.js.map (external, debug only). Release: npm run build (minified).');
	await context.watch();
}
