// esbuild.mjs — build script for the OpenRouter PDF Translator plugin.
//
// This is the STANDARD Obsidian plugin build (same shape as
// obsidian-sample-plugin's esbuild.config.mjs): no custom esbuild plugins,
// no inline checks. Everything project-specific lives in scripts/:
//
//   scripts/patch-pdfjs.mjs  — patches pdfjs-dist in node_modules so the
//                              bundled pdf.js passes the community-plugin
//                              validator. Runs automatically (postinstall
//                              + before every build/dev via npm scripts).
//   scripts/verify-bundle.mjs — post-build compliance gate (runs as part of
//                              `npm run build`, or manually: npm run verify).
//
// IMPORTANT:
//   - `pdfjs-dist` and `dompurify` must NOT be listed in `external` — they
//     are runtime dependencies bundled INTO main.js (the installed plugin
//     folder has no node_modules).
//   - pdfjs-dist must stay pinned to 3.11.174.
//   - Build via npm scripts (`npm run dev` / `npm run build`), NOT via
//     `node esbuild.mjs` directly — the npm scripts run the pdfjs patch first.
//
// NOTE: this repo uses a FLAT layout — main.ts sits next to main.js,
// esbuild.mjs and package.json in the repository root (no src/ folder).

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
    // NOTE: intentionally NOT external — must be bundled into main.js:
    //   pdfjs-dist, dompurify
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  // Dev: EXTERNAL sourcemap (main.js.map) — Obsidian loads only main.js, so
  // the dev bundle stays ~4.8 MB instead of ~15 MB with inline maps (faster
  // plugin reloads while developing); DevTools still resolves sources via the
  // emitted `//# sourceMappingURL=main.js.map` comment.
  // Production: no sourcemap — the release artifact must be self-contained.
  sourcemap: prod ? false : true,
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  console.log("[dev] watch mode: main.js (~4.8 MB) + main.js.map (external sourcemap, debug only)");
  console.log("[dev] main.js.map is NOT loaded by Obsidian — keep it out of releases (.gitignore)");
  console.log("[dev] for the RELEASE build run: npm run build");
  await context.watch();
}
